//! Command-line argument parsing and definitions for agenix.
//!
//! This module defines the CLI interface using clap's derive macros with subcommands.

use clap::{Parser, Subcommand};
use std::env;

#[derive(Parser, Debug)]
#[command(
    version = env!("CARGO_PKG_VERSION"),
    about = "edit and rekey age secret files",
    after_help = concat!("agenix version: ", env!("CARGO_PKG_VERSION"))
)]
pub struct Args {
    /// Path to Nix rules file (can also be set via RULES env var)
    #[arg(
        short = 'r',
        long,
        env = "RULES",
        value_name = "FILE",
        default_value = "./secrets.nix",
        global = true
    )]
    pub rules: String,

    /// Verbose output
    #[arg(short, long, global = true)]
    pub verbose: bool,

    /// Identity (private key) to use when decrypting. Can be specified multiple times.
    /// Identities are tried in order: explicitly specified identities first, then default system identities.
    #[arg(short, long, value_name = "KEY", global = true, action = clap::ArgAction::Append)]
    pub identity: Vec<String>,

    /// Do not use default system identities (~/.ssh/id_rsa, ~/.ssh/id_ed25519)
    #[arg(long, global = true)]
    pub no_system_identities: bool,

    #[command(subcommand)]
    pub command: Option<Command>,
}

#[derive(Subcommand, Debug)]
pub enum Command {
    /// Edit a secret file using $EDITOR (creates new file if it doesn't exist)
    #[command(visible_alias = "e")]
    Edit {
        /// The secret file to edit
        #[arg(value_name = "FILE", allow_hyphen_values = true)]
        file: String,

        /// Editor command to use (defaults to $EDITOR or vi)
        #[arg(short = 'e', long, env = "EDITOR", value_name = "COMMAND", default_value_t = String::from("vi"))]
        editor: String,
    },

    /// Encrypt content from stdin to a secret file
    #[command(visible_alias = "c")]
    Encrypt {
        /// The secret file to create
        #[arg(value_name = "FILE", allow_hyphen_values = true)]
        file: String,

        /// Overwrite existing secret file
        #[arg(short, long)]
        force: bool,
    },

    /// Decrypt a secret file to stdout or a file
    #[command(visible_alias = "d")]
    Decrypt {
        /// The secret file to decrypt
        #[arg(value_name = "FILE", allow_hyphen_values = true)]
        file: String,

        /// Output file (defaults to stdout)
        #[arg(short, long, value_name = "FILE")]
        output: Option<String>,
    },

    /// Re-encrypt secrets with updated recipients
    #[command(visible_alias = "r")]
    Rekey {
        /// Allow partial rekeying: continue even if some secrets cannot be decrypted
        #[arg(long)]
        partial: bool,

        /// Secrets to rekey (if none specified, rekeys all secrets from the rules file)
        #[arg(value_name = "SECRET")]
        secrets: Vec<String>,
    },

    /// Generate secrets using generator functions from rules
    #[command(visible_alias = "g")]
    Generate {
        /// Overwrite existing secret files
        #[arg(short, long)]
        force: bool,

        /// Show what would be generated without making changes
        #[arg(short = 'n', long)]
        dry_run: bool,

        /// Do not generate dependencies of specified secrets (dependencies are generated by default)
        #[arg(long)]
        no_dependencies: bool,

        /// Secrets to generate (if none specified, generates all secrets from the rules file)
        #[arg(value_name = "SECRET")]
        secrets: Vec<String>,
    },
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Mutex, OnceLock};

    static ENV_LOCK: OnceLock<Mutex<()>> = OnceLock::new();

    /// Helper to restore environment variable after test
    fn with_env_var<F>(key: &str, value: Option<&str>, f: F)
    where
        F: FnOnce(),
    {
        let _guard = ENV_LOCK.get_or_init(|| Mutex::new(())).lock().unwrap();
        let original = std::env::var(key).ok();

        match value {
            // SAFETY: We hold ENV_LOCK to ensure no other thread is accessing env vars
            Some(v) => unsafe { std::env::set_var(key, v) },
            None => unsafe { std::env::remove_var(key) },
        }

        f();

        match original {
            // SAFETY: We hold ENV_LOCK to ensure no other thread is accessing env vars
            Some(v) => unsafe { std::env::set_var(key, v) },
            None => unsafe { std::env::remove_var(key) },
        }
    }

    #[test]
    fn test_edit_subcommand() {
        let args = Args::try_parse_from(["agenix", "edit", "test.age"]).unwrap();
        assert!(matches!(args.command, Some(Command::Edit { .. })));
        assert!(!args.verbose);
        assert!(args.identity.is_empty());
        if let Some(Command::Edit { file, .. }) = args.command {
            assert_eq!(file, "test.age".to_string());
        }
    }

    #[test]
    fn test_edit_short_alias() {
        let args = Args::try_parse_from(["agenix", "e", "test.age"]).unwrap();
        assert!(matches!(args.command, Some(Command::Edit { .. })));
    }

    #[test]
    fn test_rekey_subcommand() {
        let args = Args::try_parse_from(["agenix", "rekey"]).unwrap();
        assert!(matches!(args.command, Some(Command::Rekey { .. })));
    }

    #[test]
    fn test_rekey_short_alias() {
        let args = Args::try_parse_from(["agenix", "r"]).unwrap();
        assert!(matches!(args.command, Some(Command::Rekey { .. })));
    }

    #[test]
    fn test_decrypt_subcommand_with_identity() {
        let args = Args::try_parse_from(["agenix", "-i", "/path/to/key", "decrypt", "secret.age"])
            .unwrap();
        assert_eq!(args.identity, vec!["/path/to/key".to_string()]);
        if let Some(Command::Decrypt { file, .. }) = args.command {
            assert_eq!(file, "secret.age".to_string());
        } else {
            panic!("Expected Decrypt command");
        }
    }

    #[test]
    fn test_decrypt_short_alias() {
        let args = Args::try_parse_from(["agenix", "d", "secret.age"]).unwrap();
        assert!(matches!(args.command, Some(Command::Decrypt { .. })));
    }

    #[test]
    fn test_encrypt_subcommand() {
        let args = Args::try_parse_from(["agenix", "encrypt", "test.age"]).unwrap();
        assert!(matches!(args.command, Some(Command::Encrypt { .. })));
        if let Some(Command::Encrypt { file, force }) = args.command {
            assert_eq!(file, "test.age".to_string());
            assert!(!force);
        } else {
            panic!("Expected Encrypt command");
        }
    }

    #[test]
    fn test_encrypt_short_alias() {
        let args = Args::try_parse_from(["agenix", "c", "test.age"]).unwrap();
        assert!(matches!(args.command, Some(Command::Encrypt { .. })));
    }

    #[test]
    fn test_encrypt_with_force() {
        let args = Args::try_parse_from(["agenix", "encrypt", "--force", "test.age"]).unwrap();
        if let Some(Command::Encrypt { file, force }) = args.command {
            assert_eq!(file, "test.age".to_string());
            assert!(force);
        } else {
            panic!("Expected Encrypt command");
        }
    }

    #[test]
    fn test_encrypt_with_force_short() {
        let args = Args::try_parse_from(["agenix", "encrypt", "-f", "test.age"]).unwrap();
        if let Some(Command::Encrypt { file, force }) = args.command {
            assert_eq!(file, "test.age".to_string());
            assert!(force);
        } else {
            panic!("Expected Encrypt command");
        }
    }

    #[test]
    fn test_verbose_flag_with_edit() {
        let args = Args::try_parse_from(["agenix", "-v", "edit", "test.age"]).unwrap();
        assert!(args.verbose);
        assert!(matches!(args.command, Some(Command::Edit { .. })));
    }

    #[test]
    fn test_verbose_flag_after_subcommand() {
        let args = Args::try_parse_from(["agenix", "edit", "-v", "test.age"]).unwrap();
        assert!(args.verbose);
        assert!(matches!(args.command, Some(Command::Edit { .. })));
    }

    #[test]
    fn test_args_parsing_default_editor() {
        with_env_var("EDITOR", None, || {
            let args = Args::try_parse_from(["agenix", "edit", "test.age"]).unwrap();
            if let Some(Command::Edit { file, editor, .. }) = args.command {
                assert_eq!(file, "test.age".to_string());
                assert_eq!(editor, "vi");
            } else {
                panic!("Expected Edit command");
            }
        });
    }

    #[test]
    fn test_editor_env_overrides_default() {
        with_env_var("EDITOR", Some("nano"), || {
            let args = Args::try_parse_from(["agenix", "edit", "test.age"]).unwrap();
            if let Some(Command::Edit { editor, .. }) = args.command {
                assert_eq!(editor, "nano");
            } else {
                panic!("Expected Edit command");
            }
        });
    }

    #[test]
    fn test_editor_flag_overrides_env() {
        with_env_var("EDITOR", Some("nano"), || {
            let args =
                Args::try_parse_from(["agenix", "edit", "--editor", "vim", "test.age"]).unwrap();
            if let Some(Command::Edit { editor, .. }) = args.command {
                assert_eq!(editor, "vim");
            } else {
                panic!("Expected Edit command");
            }
        });
    }

    #[test]
    fn test_editor_flag_without_env() {
        with_env_var("EDITOR", None, || {
            let args =
                Args::try_parse_from(["agenix", "edit", "--editor", "micro", "test.age"]).unwrap();
            if let Some(Command::Edit { editor, .. }) = args.command {
                assert_eq!(editor, "micro");
            } else {
                panic!("Expected Edit command");
            }
        });
    }

    #[test]
    fn test_rules_env_var() {
        with_env_var("RULES", Some("/custom/path/secrets.nix"), || {
            let args = Args::try_parse_from(["agenix", "generate"]).unwrap();
            assert_eq!(args.rules, "/custom/path/secrets.nix");
        });
    }

    #[test]
    fn test_generate_subcommand() {
        let args = Args::try_parse_from(["agenix", "generate"]).unwrap();
        assert!(matches!(args.command, Some(Command::Generate { .. })));
        if let Some(Command::Generate {
            force,
            dry_run,
            no_dependencies,
            secrets,
        }) = args.command
        {
            assert!(!force);
            assert!(!dry_run);
            assert!(!no_dependencies);
            assert!(secrets.is_empty());
        }
    }

    #[test]
    fn test_generate_short_alias() {
        let args = Args::try_parse_from(["agenix", "g"]).unwrap();
        assert!(matches!(args.command, Some(Command::Generate { .. })));
    }

    #[test]
    fn test_generate_force_flag() {
        let args = Args::try_parse_from(["agenix", "generate", "--force"]).unwrap();
        if let Some(Command::Generate {
            force,
            dry_run,
            no_dependencies,
            secrets,
        }) = args.command
        {
            assert!(force);
            assert!(!dry_run);
            assert!(!no_dependencies);
            assert!(secrets.is_empty());
        } else {
            panic!("Expected Generate command");
        }
    }

    #[test]
    fn test_generate_force_short_flag() {
        let args = Args::try_parse_from(["agenix", "generate", "-f"]).unwrap();
        if let Some(Command::Generate { force, dry_run, .. }) = args.command {
            assert!(force);
            assert!(!dry_run);
        } else {
            panic!("Expected Generate command");
        }
    }

    #[test]
    fn test_generate_dry_run_flag() {
        let args = Args::try_parse_from(["agenix", "generate", "--dry-run"]).unwrap();
        if let Some(Command::Generate { force, dry_run, .. }) = args.command {
            assert!(!force);
            assert!(dry_run);
        } else {
            panic!("Expected Generate command");
        }
    }

    #[test]
    fn test_generate_dry_run_short_flag() {
        let args = Args::try_parse_from(["agenix", "generate", "-n"]).unwrap();
        if let Some(Command::Generate { force, dry_run, .. }) = args.command {
            assert!(!force);
            assert!(dry_run);
        } else {
            panic!("Expected Generate command");
        }
    }

    #[test]
    fn test_generate_force_and_dry_run() {
        let args = Args::try_parse_from(["agenix", "generate", "--force", "--dry-run"]).unwrap();
        if let Some(Command::Generate { force, dry_run, .. }) = args.command {
            assert!(force);
            assert!(dry_run);
        } else {
            panic!("Expected Generate command");
        }
    }

    #[test]
    fn test_generate_short_flags_combined() {
        let args = Args::try_parse_from(["agenix", "generate", "-f", "-n"]).unwrap();
        if let Some(Command::Generate { force, dry_run, .. }) = args.command {
            assert!(force);
            assert!(dry_run);
        } else {
            panic!("Expected Generate command");
        }
    }

    #[test]
    fn test_help_contains_version() {
        use clap::CommandFactory;

        let mut cmd = Args::command();
        let help = cmd.render_help().to_string();

        // Check that help contains the version information at the end
        let expected_version_line = format!("agenix version: {}", env!("CARGO_PKG_VERSION"));
        assert!(
            help.contains(&expected_version_line),
            "Help output should contain version line: {expected_version_line}",
        );

        // Also verify it's near the end (after the Commands section)
        let commands_pos = help
            .find("Commands:")
            .expect("Help should contain Commands section");
        let version_pos = help
            .find(&expected_version_line)
            .expect("Help should contain version line");
        assert!(
            version_pos > commands_pos,
            "Version line should appear after Commands section"
        );
    }

    #[test]
    fn test_no_subcommand() {
        let args = Args::try_parse_from(["agenix"]).unwrap();
        assert!(args.command.is_none());
    }

    #[test]
    fn test_decrypt_with_output() {
        let args =
            Args::try_parse_from(["agenix", "decrypt", "secret.age", "-o", "/path/to/output"])
                .unwrap();
        if let Some(Command::Decrypt { file, output, .. }) = args.command {
            assert_eq!(file, "secret.age".to_string());
            assert_eq!(output, Some("/path/to/output".to_string()));
        } else {
            panic!("Expected Decrypt command");
        }
    }

    #[test]
    fn test_global_rules_option() {
        let args =
            Args::try_parse_from(["agenix", "--rules", "/custom/rules.nix", "generate"]).unwrap();
        assert_eq!(args.rules, "/custom/rules.nix");
        assert!(matches!(args.command, Some(Command::Generate { .. })));
    }

    #[test]
    fn test_global_rules_short_flag() {
        let args = Args::try_parse_from(["agenix", "-r", "/custom/rules.nix", "generate"]).unwrap();
        assert_eq!(args.rules, "/custom/rules.nix");
        assert!(matches!(args.command, Some(Command::Generate { .. })));
    }

    #[test]
    fn test_edit_editor_short_flag() {
        let args = Args::try_parse_from(["agenix", "edit", "-e", "nano", "test.age"]).unwrap();
        if let Some(Command::Edit { editor, .. }) = args.command {
            assert_eq!(editor, "nano");
        } else {
            panic!("Expected Edit command");
        }
    }

    // Tests to ensure old flag-based interface no longer works
    // These verify that the migration to subcommands is complete

    #[test]
    fn test_old_edit_flag_rejected() {
        // Old: agenix -e file.age
        // New: agenix edit file.age
        let result = Args::try_parse_from(["agenix", "-e", "test.age"]);
        assert!(result.is_err(), "Old -e flag should be rejected");
    }

    #[test]
    fn test_old_edit_long_flag_rejected() {
        // Old: agenix --edit file.age
        let result = Args::try_parse_from(["agenix", "--edit", "test.age"]);
        assert!(result.is_err(), "Old --edit flag should be rejected");
    }

    #[test]
    fn test_old_decrypt_flag_rejected() {
        // Old: agenix -d file.age
        // New: agenix decrypt file.age
        let result = Args::try_parse_from(["agenix", "-d", "test.age"]);
        assert!(result.is_err(), "Old -d flag should be rejected");
    }

    #[test]
    fn test_old_decrypt_long_flag_rejected() {
        // Old: agenix --decrypt file.age
        let result = Args::try_parse_from(["agenix", "--decrypt", "test.age"]);
        assert!(result.is_err(), "Old --decrypt flag should be rejected");
    }

    #[test]
    fn test_rules_short_flag_requires_value() {
        // -r is now for --rules and requires a value
        let result = Args::try_parse_from(["agenix", "-r"]);
        assert!(result.is_err(), "-r requires a value");
    }

    #[test]
    fn test_old_rekey_long_flag_rejected() {
        // Old: agenix --rekey
        let result = Args::try_parse_from(["agenix", "--rekey"]);
        assert!(result.is_err(), "Old --rekey flag should be rejected");
    }

    #[test]
    fn test_old_generate_flag_rejected() {
        // Old: agenix -g
        // New: agenix generate
        let result = Args::try_parse_from(["agenix", "-g"]);
        assert!(result.is_err(), "Old -g flag should be rejected");
    }

    #[test]
    fn test_old_generate_long_flag_rejected() {
        // Old: agenix --generate
        let result = Args::try_parse_from(["agenix", "--generate"]);
        assert!(result.is_err(), "Old --generate flag should be rejected");
    }

    #[test]
    fn test_global_identity_flag_at_root_works() {
        // Now: agenix -i key edit file.age (identity at root level works)
        let result = Args::try_parse_from(["agenix", "-i", "/path/to/key", "edit", "test.age"]);
        assert!(
            result.is_ok(),
            "Global -i flag at root level should be accepted"
        );
        let args = result.unwrap();
        assert_eq!(args.identity, vec!["/path/to/key".to_string()]);
    }

    #[test]
    fn test_old_output_flag_at_root_rejected() {
        // Old: agenix -o output -d file.age (output at root level)
        // New: agenix decrypt -o output file.age (output in subcommand)
        let result = Args::try_parse_from(["agenix", "-o", "output.txt", "decrypt", "test.age"]);
        assert!(
            result.is_err(),
            "Old -o flag at root level should be rejected"
        );
    }

    // Tests for global identity flag - only essential coverage

    #[test]
    fn test_identity_before_subcommand() {
        let args =
            Args::try_parse_from(["agenix", "-i", "/path/to/key", "edit", "secret.age"]).unwrap();
        assert_eq!(args.identity, vec!["/path/to/key".to_string()]);
        assert!(matches!(args.command, Some(Command::Edit { .. })));
    }

    #[test]
    fn test_identity_after_subcommand() {
        let args = Args::try_parse_from(["agenix", "decrypt", "-i", "/path/to/key", "secret.age"])
            .unwrap();
        assert_eq!(args.identity, vec!["/path/to/key".to_string()]);
        assert!(matches!(args.command, Some(Command::Decrypt { .. })));
    }

    #[test]
    fn test_multiple_identities_order_preserved() {
        let args = Args::try_parse_from([
            "agenix",
            "-i",
            "/first",
            "-i",
            "/second",
            "-i",
            "/third",
            "decrypt",
            "secret.age",
        ])
        .unwrap();
        assert_eq!(
            args.identity,
            vec![
                "/first".to_string(),
                "/second".to_string(),
                "/third".to_string()
            ]
        );
    }

    #[test]
    fn test_no_system_identities_flag() {
        let args =
            Args::try_parse_from(["agenix", "--no-system-identities", "decrypt", "secret.age"])
                .unwrap();
        assert!(args.no_system_identities);
    }

    #[test]
    fn test_identity_with_no_system_identities_combined() {
        let args = Args::try_parse_from([
            "agenix",
            "-i",
            "/key1",
            "--no-system-identities",
            "decrypt",
            "secret.age",
        ])
        .unwrap();
        assert_eq!(args.identity, vec!["/key1".to_string()]);
        assert!(args.no_system_identities);
    }

    // Tests for positional secrets argument in rekey

    #[test]
    fn test_rekey_with_positional_secrets() {
        let args = Args::try_parse_from(["agenix", "rekey", "secret1.age", "secret2.age"]).unwrap();
        if let Some(Command::Rekey { secrets, .. }) = args.command {
            assert_eq!(
                secrets,
                vec!["secret1.age".to_string(), "secret2.age".to_string()]
            );
        } else {
            panic!("Expected Rekey command");
        }
    }

    #[test]
    fn test_rekey_without_positional_secrets() {
        let args = Args::try_parse_from(["agenix", "rekey"]).unwrap();
        if let Some(Command::Rekey { secrets, .. }) = args.command {
            assert!(secrets.is_empty());
        } else {
            panic!("Expected Rekey command");
        }
    }

    #[test]
    fn test_rekey_single_secret() {
        let args = Args::try_parse_from(["agenix", "rekey", "single.age"]).unwrap();
        if let Some(Command::Rekey { secrets, .. }) = args.command {
            assert_eq!(secrets, vec!["single.age".to_string()]);
        } else {
            panic!("Expected Rekey command");
        }
    }

    // Tests for positional secrets argument in generate

    #[test]
    fn test_generate_with_positional_secrets() {
        let args =
            Args::try_parse_from(["agenix", "generate", "secret1.age", "secret2.age"]).unwrap();
        if let Some(Command::Generate { secrets, .. }) = args.command {
            assert_eq!(
                secrets,
                vec!["secret1.age".to_string(), "secret2.age".to_string()]
            );
        } else {
            panic!("Expected Generate command");
        }
    }

    #[test]
    fn test_generate_without_positional_secrets() {
        let args = Args::try_parse_from(["agenix", "generate"]).unwrap();
        if let Some(Command::Generate { secrets, .. }) = args.command {
            assert!(secrets.is_empty());
        } else {
            panic!("Expected Generate command");
        }
    }

    #[test]
    fn test_generate_single_secret() {
        let args = Args::try_parse_from(["agenix", "generate", "single.age"]).unwrap();
        if let Some(Command::Generate { secrets, .. }) = args.command {
            assert_eq!(secrets, vec!["single.age".to_string()]);
        } else {
            panic!("Expected Generate command");
        }
    }

    #[test]
    fn test_generate_no_dependencies_flag() {
        let args = Args::try_parse_from(["agenix", "generate", "--no-dependencies", "secret.age"])
            .unwrap();
        if let Some(Command::Generate {
            no_dependencies,
            secrets,
            ..
        }) = args.command
        {
            assert!(no_dependencies);
            assert_eq!(secrets, vec!["secret.age".to_string()]);
        } else {
            panic!("Expected Generate command");
        }
    }

    #[test]
    fn test_generate_with_flags_and_positional_secrets() {
        let args = Args::try_parse_from([
            "agenix",
            "generate",
            "--force",
            "--dry-run",
            "secret1.age",
            "secret2.age",
        ])
        .unwrap();
        if let Some(Command::Generate {
            force,
            dry_run,
            secrets,
            ..
        }) = args.command
        {
            assert!(force);
            assert!(dry_run);
            assert_eq!(
                secrets,
                vec!["secret1.age".to_string(), "secret2.age".to_string()]
            );
        } else {
            panic!("Expected Generate command");
        }
    }

    #[test]
    fn test_generate_secrets_after_flags() {
        let args = Args::try_parse_from([
            "agenix",
            "generate",
            "-f",
            "-n",
            "--no-dependencies",
            "a.age",
            "b.age",
        ])
        .unwrap();
        if let Some(Command::Generate {
            force,
            dry_run,
            no_dependencies,
            secrets,
        }) = args.command
        {
            assert!(force);
            assert!(dry_run);
            assert!(no_dependencies);
            assert_eq!(secrets, vec!["a.age".to_string(), "b.age".to_string()]);
        } else {
            panic!("Expected Generate command");
        }
    }

    // Tests for rekey --partial flag

    #[test]
    fn test_rekey_partial_flag() {
        let args = Args::try_parse_from(["agenix", "rekey", "--partial"]).unwrap();
        if let Some(Command::Rekey { partial, secrets }) = args.command {
            assert!(partial);
            assert!(secrets.is_empty());
        } else {
            panic!("Expected Rekey command");
        }
    }

    #[test]
    fn test_rekey_partial_with_secrets() {
        let args =
            Args::try_parse_from(["agenix", "rekey", "--partial", "secret1.age", "secret2.age"])
                .unwrap();
        if let Some(Command::Rekey { partial, secrets }) = args.command {
            assert!(partial);
            assert_eq!(
                secrets,
                vec!["secret1.age".to_string(), "secret2.age".to_string()]
            );
        } else {
            panic!("Expected Rekey command");
        }
    }

    #[test]
    fn test_rekey_default_not_partial() {
        let args = Args::try_parse_from(["agenix", "rekey"]).unwrap();
        if let Some(Command::Rekey { partial, secrets }) = args.command {
            assert!(!partial);
            assert!(secrets.is_empty());
        } else {
            panic!("Expected Rekey command");
        }
    }
}
