name: "CI"
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            system-features = nixos-test recursive-nix benchmark big-parallel kvm
            experimental-features = recursive-nix nix-command flakes
      - run: nix fmt . -- --ci
  tests:
    strategy:
      fail-fast: false
      matrix:
        # macOS is intentionally not tested; macOS support is out of scope
        # for now.
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            system-features = nixos-test recursive-nix benchmark big-parallel kvm
            experimental-features = recursive-nix nix-command flakes
      - run: nix build
      - run: nix build .#doc
      - run: nix flake check --print-build-logs
